apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraformacrsntdr-deployment
  labels:
    app: terraformacrsntdr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraformacrsntdr
  template:
    metadata:
      labels:
        app: terraformacrsntdr
    spec:
      containers:
        - name: terraformacrsntdr 
          image: terraformacrsntdr.azurecr.io/santander/demoappnet
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: terraformacrsntdr-loadbalancer-service
  labels:
    app: terraformacrsntdr
spec:
  type: LoadBalancer
  selector:
    app: terraformacrsntdr
  ports:
    - port: 80
      targetPort: 80